#!/usr/bin/env bash
# install and configure ufw in an ubuntu machine
sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo ufw reload
# check connection status
sudo ufw status verbose
