#!/usr/bin/env bash
# ufw redirect port 8080 to port 80
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-ports 80
sudo iptables-save
sudo iptables -t nat -L
sudo systemctl restart ufw
