#!/usr/bin/env bash
# changes the following domain resolve ips
#   localhost from 127.0.0.1 to 127.0.0.2
#   facebook.com from 157.240.11.35 to 8.8.8.8

echo "127.0.0.2 localhost" >> /etc/hosts

# Add facebook.com entry to /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

# Restart netwoking service connection
systemctl restart networking.service
