#!/usr/bin/env bash
# Displays all acive IPv4 addresses on the machine.

# a different way using ifconfig but now ip is a new command and ifconfig can be missing in some os
#ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'

ipv4_addresses=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Print the IPv4 addresses
echo "Active IPv4 addresses:"
echo "$ipv4_addresses"
