#!/usr/bin/env bash
# Running Nginx as nginx user instead of root
sudo adduser --system --no-create-home --disabled-login --disabled-password --group nginx
sudo chmod 777 nginx
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx restart
