#!/usr/bin/env bash
# Task 1 in a short and sweet 7 lines or less
adduser --system --disabled-password nginx
chmod 777 nginx
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx reload
