#!/usr/bin/env bash
# Short and sweet
sudo adduser --system --no-create-home --disabled-login --disabled-password --group nginx
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
